sonar.projectKey=Forge-Space_forgespace-web
sonar.organization=forge-space
sonar.projectName=forgespace-web

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/components/shared/HeroParticlesBackground.tsx,src/components/landing/HeroSection.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,src/__tests__/**,src/types/**,**/*.test.ts,**/*.test.tsx
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx
