"use client";

import { motion } from "motion/react";
import { Lock, Layers } from "lucide-react";
import { GitHubIcon } from "@/components/shared/GitHubIcon";
import { EASE_SIZA } from "@/lib/constants";

interface FeaturesGridProps {
  repoCount: number;
}

const quickFeatures = [
  {
    icon: <GitHubIcon className="w-4 h-4 text-forge-primary" />,
    title: "Open-Source Foundation",
    description: "Core repositories and packages are public under MIT License.",
  },
  {
    icon: <Layers className="w-4 h-4 text-forge-primary" />,
    title: "Composable Architecture",
    description: "Combine governance and delivery modules through MCP — each layer independently replaceable.",
  },
];

export function FeaturesGrid({ repoCount }: FeaturesGridProps) {
  return (
    <div>
      {/* Section header */}
      <div className="max-w-6xl mx-auto px-6 pt-12 pb-10">
        <p className="text-xs font-mono uppercase tracking-[0.2em] text-forge-primary mb-3">
          Features
        </p>
        <h2 className="text-display-lg font-display font-bold tracking-tight leading-tight mb-4">
          Built for developers who ship
        </h2>
        <p className="text-xl text-forge-text-muted max-w-2xl">
          A complete delivery stack across {repoCount} actively maintained repos,
          with governance built into the generation loop.
        </p>
      </div>

      {/* Feature 1: AI-Powered Generation — text left, mockup right */}
      <section aria-label="AI-Powered Generation" className="py-14 md:py-20">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-14 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA }}
            >
              <p className="text-xs font-mono uppercase tracking-[0.2em] text-forge-primary mb-3">
                01
              </p>
              <h3 className="text-3xl font-display font-bold tracking-tight leading-snug mb-4">
                Describe it. Get production code.
              </h3>
              <p className="text-lg text-forge-text-muted leading-relaxed">
                Natural language to typed, reviewable UI. Siza understands your design
                system and generates components that fit your codebase.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA, delay: 0.1 }}
            >
              <div className="bg-[#0d0d0f] border border-forge-border rounded-xl overflow-hidden">
                <div className="p-4 font-mono text-xs leading-relaxed overflow-x-auto">
                <pre className="text-forge-text-muted whitespace-pre">
                  <code>
                    <span className="text-forge-text-subtle italic">{"// Generated by Siza"}</span>
                    {"\n"}
                    <span className="text-violet-400">export function</span>
                    {" "}
                    <span className="text-sky-400">UserCard</span>
                    {"({ user }: UserCardProps) {"}
                    {"\n  "}
                    <span className="text-violet-400">return</span>
                    {"(\n    "}
                    <span className="text-sky-400">{"<Card"}</span>
                    {" "}
                    <span className="text-forge-text-muted">className=</span>
                    <span className="text-emerald-400">{'"p-4 flex gap-3 items-center"'}</span>
                    <span className="text-sky-400">{">"}</span>
                    {"\n      "}
                    <span className="text-sky-400">{"<Avatar"}</span>
                    {" "}
                    <span className="text-forge-text-muted">src=</span>
                    {"{"}
                    <span className="text-forge-text-muted">user.avatar</span>
                    {"} "}
                    <span className="text-sky-400">{"/>"}</span>
                    {"\n      "}
                    <span className="text-sky-400">{"<p"}</span>
                    {" "}
                    <span className="text-forge-text-muted">className=</span>
                    <span className="text-emerald-400">{'"font-medium"'}</span>
                    <span className="text-sky-400">{">"}  </span>
                    {"{user.name} "}
                    <span className="text-sky-400">{"</p>"}</span>
                    {"\n    "}
                    <span className="text-sky-400">{"</Card>"}</span>
                    {"\n  );\n}"}
                  </code>
                </pre>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Feature 2: MCP-Native Architecture — mockup left, text right */}
      <section aria-label="MCP-Native Architecture" className="py-14 md:py-20 border-t border-forge-border">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-14 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA }}
              className="flex flex-col items-center justify-center"
            >
              <div className="flex items-center justify-center flex-wrap gap-2">
                <div className="border border-forge-border rounded-lg px-4 py-2 text-sm text-forge-text-muted bg-forge-surface">
                  Your LLM
                </div>
                <span className="text-forge-primary text-xl mx-2">→</span>
                <div className="border border-forge-border rounded-lg px-4 py-2 text-sm text-forge-text-muted bg-forge-surface">
                  MCP Gateway
                </div>
                <span className="text-forge-primary text-xl mx-2">→</span>
                <div className="border border-forge-primary/40 rounded-lg px-4 py-2 text-sm text-forge-primary bg-forge-primary/5">
                  Siza
                </div>
              </div>
              <p className="text-xs text-forge-text-subtle mt-4 text-center">
                Plug in Gemini, Claude, or GPT — same governance layer.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA, delay: 0.1 }}
            >
              <p className="text-xs font-mono uppercase tracking-[0.2em] text-forge-primary mb-3">
                02
              </p>
              <h3 className="text-3xl font-display font-bold tracking-tight leading-snug mb-4">
                Every capability, swappable.
              </h3>
              <p className="text-lg text-forge-text-muted leading-relaxed">
                Generation, governance, branding, and migration are composed through
                MCP — each layer independently replaceable without forking the platform.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Feature 3: CI Quality Gates — text left, mockup right */}
      <section aria-label="CI Quality Gates" className="py-14 md:py-20 border-t border-forge-border">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-14 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA }}
            >
              <p className="text-xs font-mono uppercase tracking-[0.2em] text-forge-primary mb-3">
                03
              </p>
              <h3 className="text-3xl font-display font-bold tracking-tight leading-snug mb-4">
                Quality gates in every PR.
              </h3>
              <p className="text-lg text-forge-text-muted leading-relaxed">
                forge-ai-action runs scoring, annotations, and threshold enforcement
                automatically in your GitHub workflow — no dashboard required.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA, delay: 0.1 }}
            >
              <div className="border border-forge-border rounded-xl bg-forge-surface overflow-hidden border-l-4 border-l-violet-500">
                <div className="flex items-center justify-between px-4 py-3 border-b border-forge-border">
                  <span className="font-mono text-sm text-forge-text-muted">
                    forge-ai-action
                  </span>
                  <span className="flex items-center gap-1.5 text-xs font-medium text-violet-400 bg-violet-400/10 px-2 py-0.5 rounded-full">
                    ✓ passed
                  </span>
                </div>
                <div className="px-4 py-3 space-y-2 font-mono text-sm">
                  <div className="flex items-center justify-between">
                    <span className="text-forge-text-muted">Score</span>
                    <span className="text-emerald-400">94/100</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-forge-text-muted">Components reviewed</span>
                    <span className="text-foreground/80">23</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-forge-text-muted">Warnings</span>
                    <span className="text-amber-400">2</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-forge-text-muted">Errors</span>
                    <span className="text-emerald-400">0</span>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Feature 4: Privacy-First BYOK — mockup left, text right */}
      <section aria-label="Privacy-First BYOK" className="py-14 md:py-20 border-t border-forge-border">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-14 items-center">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA }}
              className="flex flex-col items-center justify-center"
            >
              <div className="flex h-20 w-20 items-center justify-center rounded-full bg-violet-500/20">
                <Lock className="h-10 w-10 text-violet-400" />
              </div>
              <p className="text-xs text-forge-text-subtle mt-4 text-center tracking-wider">
                AES-256 · Client-side only · MIT License
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: EASE_SIZA, delay: 0.1 }}
            >
              <p className="text-xs font-mono uppercase tracking-[0.2em] text-forge-primary mb-3">
                04
              </p>
              <h3 className="text-3xl font-display font-bold tracking-tight leading-snug mb-4">
                Your keys. Your infra. Your rules.
              </h3>
              <p className="text-lg text-forge-text-muted leading-relaxed">
                Client-side AES-256 encryption means your API keys never touch our
                servers. Self-host the full stack under MIT — or run it locally with Docker.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Quick feature grid — Open-Source Foundation + Composable Architecture */}
      <section aria-label="Platform foundations" className="border-t border-forge-border">
        <div className="max-w-6xl mx-auto px-6 py-10">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {quickFeatures.map((feat, i) => (
              <motion.div
                key={feat.title}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, ease: EASE_SIZA, delay: i * 0.07 }}
                className="flex items-start gap-4 rounded-xl border border-forge-border bg-forge-surface/50 p-5"
              >
                <div className="mt-0.5 flex-shrink-0 flex items-center justify-center w-8 h-8 rounded-lg bg-forge-primary/10">
                  {feat.icon}
                </div>
                <div>
                  <p className="text-sm font-semibold text-foreground mb-1">{feat.title}</p>
                  <p className="text-sm text-forge-text-muted leading-relaxed">{feat.description}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section aria-label="Multi-Model Workflows" className="sr-only">
        <h3>Multi-Model Workflows</h3>
      </section>
    </div>
  );
}
